server.port=8081

spring.application.name=blps_check_sender

rabbitmq.url=amqp://localhost:5672
rabbitmq.queue=checks.queue
rabbitmq.username=admin
rabbitmq.password=admin

onec.url=localhost/blps/hs/v1/receipts

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rmr04489@gmail.com
spring.mail.password=ghedqrubdyppenlp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
