server.port=8081

spring.application.name=blps_check_sender

rabbitmq.url=amqp://localhost:5672
rabbitmq.queue=checks.queue
rabbitmq.queue.dead=dead.queue
rabbitmq.username=admin
rabbitmq.password=admin

onec.url=http://localhost/blps/hs/v1/receipts

spring.mail.host=smtp.yandex.ru
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=rmr04
spring.mail.password=?????? ????
